# .github/workflows/main.yml
name: Test, Build, and Deploy with GameCI
on:
 push:
 branches:
 — develop
 paths:
 — ‘Assets/**’
 — ‘Packages/**’
 — ‘ProjectSettings/**’
 pull_request:
 types:
 — opened
 branches:
 — main
 paths:
 — ‘Assets/**’
 — ‘Packages/**’
 — ‘ProjectSettings/**’
 release:
 types:
 — published
 workflow_dispatch:
 inputs:
 workflow_mode:
 description: ‘[release] [WebGL]’
 required: false
 default: ‘’
jobs:
